---
title: "Team Registration and Proposal"
output: github_document
date: "2024-11-07"
---

### Group member [UNI]:
<br>
Anni Wang [aw3621]
<br>
Yifan Shi [ys3766] 
<br>
Qi Cai [qc2337] 
<br>
Xi Peng[xp2213]

```{r setup, include=FALSE}
library(tidyverse)
```

### The tentative project title: 
Understanding the Impact of Active Design on Physical Activity and Transportation in New York City

### The motivation for this project: 
New York City’s efforts to enhance public health through urban design, transportation infrastructure, and active living environments are crucial for promoting physical activity, reducing transportation-related injuries, and improving community health outcomes. By analyzing walkability, physical activity rates, commuting modes, and transportation-related injuries, this project aims to understand how active design principles contribute to or hinder public health in NYC neighborhoods. This project is motivated by a need to identify urban design factors that effectively promote health, safety, and well-being across diverse communities in NYC.

### The intended final products:(need to be edited later)
This project will generate a comprehensive report that includes data analysis, findings, and policy recommendations. This report will cover:

- Descriptive summaries of walkability, physical activity, transportation modes, and injury rates across NYC neighborhoods.

- Correlations and associations between these indicators, with insights into how urban design impacts health and safety.

- Geospatial visualization showing the distribution of walkability, physical activity levels, commuting methods, and injury rates across NYC neighborhoods.

- Recommendations for urban planning and public health policy based on the findings, targeting specific NYC neighborhoods or boroughs.


### The anticipated data sources:

We will be using the environment and health data published by [nyc.gov](https://a816-dohbesp.nyc.gov/IndicatorPublic/data-explorer/)

### The planned analyses / visualizations / coding challenges:

1. **Data Cleaning and Integration**
   - Standardize variable names, data types, and formats across multiple datasets (active design, physical activity, socioeconomic indicators, transportation modes, injury data, and health outcomes).
   - Merge datasets by common identifiers, such as geographic boundaries (borough, neighborhood), and time (if available).
   - Handle missing data and potential outliers by implementing data imputation or exclusion criteria to maintain data quality.

2. **Statistical Analysis**
   - Calculate summary statistics (mean, median, range) for each indicator within boroughs and neighborhoods to provide an overview of the data distribution.
   - Generate correlation matrices for key indicators to explore relationships between walkability, physical activity, and injury rates.
   - Carry out regression analysis to examine the relationships between walkability and key health outcomes, such as physical activity levels and transportation-related injuries.

3. **Visualization**
   - Map the distribution of key indicators like walkability scores, physical activity levels, and transportation-related injuries across NYC boroughs and neighborhoods.
   - Conduct a hotspot analysis and develop heatmaps to identify areas with particularly high or low walkability, activity levels, or injury rates.

4. **Coding Challenges**
   - The data wrangling is complex, as it involves linking multiple large datasets from different sources. They may have varying formats, missing values, and inconsistent naming conventions. Merging and standardizing these datasets for analysis can be time-consuming and error-prone.
   - Working with geospatial data (e.g., neighborhood boundaries) requires accurate geographic information for correct mapping.
   - Including many predictors may lead to multicollinearity, making it difficult to interpret model coefficients and reducing model stability.
   



