---
title: "Team Registration and Proposal"
output: github_document
date: "2024-11-07"
---

### Group member [UNI]:
<br>
Anni Wang [aw3621]
<br>
Yifan Shi [ys3766] 
<br>
Qi Cai [qc2337] 
<br>
Xi Peng[xp2213]

```{r setup, include=FALSE}
library(tidyverse)
```

### The tentative project title: 
Understanding the Impact of Active Design on Physical Activity and Transportation in New York City

### The motivation for this project: 
New York City’s efforts to enhance public health through urban design, transportation infrastructure, and active living environments are crucial for promoting physical activity, reducing transportation-related injuries, and improving community health outcomes. By analyzing walkability, physical activity rates, commuting modes, and transportation-related injuries, this project aims to understand how active design principles contribute to or hinder public health in NYC neighborhoods. This project is motivated by a need to identify urban design factors that effectively promote health, safety, and well-being across diverse communities in NYC.

### The intended final products:(need to be edited later)
This project aims to provide a comprehensive, user-friendly guide that maps out public restroom locations across the city. By leveraging open data sources, this guide will help alleviate the stress of finding a toilet in NYC, enhancing the overall experience for tourists and residents. The goal is to ensure that everyone can explore the city with confidence, knowing that they have reliable information on where to find necessary amenities, including which facilities are truly available to the public without any prerequisites.

### The anticipated [data sources](https://a816-dohbesp.nyc.gov/IndicatorPublic/data-explorer/):
The latest public restroom data extracted from the NYC Open Data website.

### The planned analyses / visualizations / coding challenges:
#### Planned analyses:
Data Cleaning and Preprocessing: Our first step will involve rigorous data cleaning and preprocessing to ensure accuracy and usability. This will include handling missing values, verifying the accuracy of the location data, and standardizing restroom facility attributes (such as accessibility features and hours of operation) for consistent analysis.

Geospatial Analysis:
We plan to perform geospatial analysis to identify areas within NYC that are underserved by public restroom facilities. By integrating the restroom data with maps and demographic information, we can highlight neighborhoods where improvements are needed, potentially influencing urban planning and accessibility efforts.

Usage Patterns and Predictive Modelling:
We aim to analyze patterns of restroom availability and predict potential high-demand areas. This could involve temporal analysis to understand peak times and seasons for restroom usage, helping tourists and locals plan their outings more effectively.

#### Visualization:
Heatmaps of Restroom Availability: To illustrate restroom density and accessibility, we will create heatmaps that show how well different parts of the city are served. This visualization will help identify "restroom deserts" and can be used for advocacy and planning.
Demand Forecast Graphs: Using predictive models, we will create graphs that forecast restroom demand across different times and areas, helping to manage and plan for peak times.

#### Coding challenges: 
Creating an intuitive for the interactive maps and other tools poses a significant challenge.


